const solutionsData = [
  {
    no: "1",
    name: "adele",
    chapter: "608",
    episode: "527",
    year: "2010",
    note: "Namanya diungkapkan dalam Blue Deep data book.",
  },
  {
    no: "2",
    name: "andre",
    chapter: "558",
    episode: "479",
    year: "2009",
    note: "Namanya diungkapkan dalam Green data book.",
  },
  {
    no: "3",
    name: "arrow",
    chapter: "196",
    episode: "120",
    year: "2001",
    note: "Namanya diungkapkan dalam Blue data book.",
  },
  {
    no: "4",
    name: "atmos",
    chapter: "553",
    episode: "461",
    year: "2009",
    note: "-",
  },
  {
    no: "5",
    name: "barry",
    chapter: "552",
    episode: "461",
    year: "2009",
    note: "Namanya diungkapkan dalam One Piece Magazine Vol.2.",
  },
  {
    no: "6",
    name: "bingo",
    chapter: "928",
    episode: "-",
    year: "2018",
    note: "-",
  },
  {
    no: "7",
    name: "bomba",
    chapter: "711",
    episode: "641",
    year: "2013",
    note: "Namanya diungkapkan dalam SBS Volume 73.",
  },
  {
    no: "8",
    name: "brahm",
    chapter: "196",
    episode: "120",
    year: "2001",
    note: "Namanya diungkapkan dalam Blue data book.",
  },
  {
    no: "9",
    name: "brogy",
    chapter: "116",
    episode: "071",
    year: "2000",
    note: "-",
  },
  {
    no: "10",
    name: "brook",
    chapter: "442",
    episode: "337",
    year: "2007",
    note: "-",
  },
  {
    no: "11",
    name: "buche",
    chapter: "880",
    episode: "852",
    year: "2017",
    note: "-",
  },
  {
    no: "12",
    name: "buchi",
    chapter: "031",
    episode: "013",
    year: "1999",
    note: "-",
  },
  {
    no: "13",
    name: "buggy",
    chapter: "009",
    episode: "004",
    year: "1997",
    note: "Dia pertama kali disebutkan olehthe Tightrope Walking Funan Bros in Chapter 8.",
  },
  {
    no: "14",
    name: "byron",
    chapter: "501",
    episode: "395",
    year: "2008",
    note: "-",
  },
  {
    no: "15",
    name: "camel",
    chapter: "695",
    episode: "621",
    year: "2013",
    note: "Its name was revealed in SBS Volume 70.",
  },
  {
    no: "16",
    name: "camel",
    chapter: "929",
    episode: "-",
    year: "-",
    note: "-",
  },
  {
    no: "17",
    name: "cands",
    chapter: "569",
    episode: "-",
    year: "2010",
    note: "Namanya diungkapkan dalam Green data book.",
  },
  {
    no: "18",
    name: "candy",
    chapter: "510",
    episode: "-",
    year: "2010",
    note: "Namanya diungkapkan dalam Vivre Card - One Piece Visual Dictionary.",
  },
  {
    no: "19",
    name: "carne",
    chapter: "045",
    episode: "021",
    year: "1998",
    note: "Namanya diungkapkan dalam Chapter 53.",
  },
  {
    no: "20",
    name: "chabo",
    chapter: "069",
    episode: "031",
    year: "1999",
    note: "Namanya diungkapkan dalam Chapter 70.",
  },
  {
    no: "21",
    name: "chaka",
    chapter: "155",
    episode: "091",
    year: "2000",
    note: "Namanya diungkapkan dalam Chapter 167.",
  },
  {
    no: "22",
    name: "chess",
    chapter: "131",
    episode: "078",
    year: "2000",
    note: "Namanya diungkapkan dalam Chapter 135.",
  },
  {
    no: "23",
    name: "cocoa",
    chapter: "598",
    episode: "518",
    year: "2010",
    note: "Her name was revealed by Demaro Black in Chapter 599.",
  },
  {
    no: "24",
    name: "cocox",
    chapter: "022",
    episode: "018",
    year: "1998",
    note: "Namanya diungkapkan dalam Blue data book.",
  },
  {
    no: "25",
    name: "comil",
    chapter: "289",
    episode: "421",
    year: "2003",
    note: "His name was revealed on the Cover Page of Chapter 290.",
  },
  {
    no: "26",
    name: "conis",
    chapter: "239",
    episode: "154",
    year: "2002",
    note: "-",
  },
  {
    no: "27",
    name: "corgi",
    chapter: "328",
    episode: "233",
    year: "2004",
    note: "-",
  },
  {
    no: "28",
    name: "cosmo",
    chapter: "450 (cover)",
    episode: "-",
    year: "2007",
    note: "Cover story character. Namanya diungkapkan dalam Blue Deep data book.",
  },
  {
    no: "29",
    name: "daisy",
    chapter: "516",
    episode: "410",
    year: "2008",
    note: "-",
  },
  {
    no: "30",
    name: "disco",
    chapter: "500",
    episode: "394",
    year: "2008",
    note: "-",
  },
  {
    no: "31",
    name: "dobon",
    chapter: "926",
    episode: "-",
    year: "2018",
    note: "-",
  },
  {
    no: "32",
    name: "doc q",
    chapter: "223",
    episode: "146",
    year: "2002",
    note: "Namanya diungkapkan dalam Chapter 234.",
  },
  {
    no: "33",
    name: "dogra",
    chapter: "582",
    episode: "493",
    year: "2010",
    note: "Namanya diungkapkan olehCurly Dadan in Chapter 584, he is formally identified in Chapter 587.",
  },
  {
    no: "34",
    name: "dogya",
    chapter: "552",
    episode: "461",
    year: "2009",
    note: "Namanya diungkapkan dalam One Piece Magazine Vol.2.",
  },
  {
    no: "35",
    name: "doran",
    chapter: "657",
    episode: "583",
    year: "2012",
    note: "Namanya diungkapkan dalam Chapter 665.",
  },
  {
    no: "36",
    name: "dorry",
    chapter: "116",
    episode: "071",
    year: "2000",
    note: "-",
  },
  {
    no: "37",
    name: "dosun",
    chapter: "611",
    episode: "530",
    year: "2011",
    note: "-",
  },
  {
    no: "38",
    name: "duval",
    chapter: "491",
    episode: "386",
    year: "2008",
    note: "Namanya diungkapkan dalam Chapter 492.",
  },
  {
    no: "39",
    name: "egana",
    chapter: "483",
    episode: "375",
    year: "2007",
    note: "Namanya diungkapkan dalam Blue Deep data book.",
  },
  {
    no: "40",
    name: "époni",
    chapter: "841",
    episode: "804",
    year: "2016",
    note: "-",
  },
  {
    no: "41",
    name: "farul",
    chapter: "722",
    episode: "634",
    year: "2013",
    note: "-",
  },
  {
    no: "42",
    name: "faust",
    chapter: "508",
    episode: "401",
    year: "2008",
    note: "Namanya diungkapkan dalam SBS Volume 86.",
  },
  {
    no: "43",
    name: "fossa",
    chapter: "553",
    episode: "461",
    year: "2009",
    note: "Namanya diungkapkan dalam SBS Volume 58.",
  },
  {
    no: "44",
    name: "genbo",
    chapter: "249",
    episode: "163",
    year: "2002",
    note: "Namanya diungkapkan olehWiper in Chapter 251.",
  },
  {
    no: "45",
    name: "genzo",
    chapter: "071",
    episode: "032",
    year: "1999",
    note: "-",
  },
  {
    no: "46",
    name: "gerth",
    chapter: "866",
    episode: "836",
    year: "2017",
    note: "-",
  },
  {
    no: "47",
    name: "glove",
    chapter: "427",
    episode: "309",
    year: "2006",
    note: "-",
  },
  {
    no: "48",
    name: "gonbe",
    chapter: "322",
    episode: "229",
    year: "2004",
    note: "-",
  },
  {
    no: "49",
    name: "gotti",
    chapter: "825",
    episode: "783",
    year: "2016",
    note: "-",
  },
  {
    no: "50",
    name: "gyaro",
    chapter: "197 (cover)",
    episode: "394",
    year: "2001",
    note: "Namanya diungkapkan dalam Blue data book. He is formally introduced in Chapter 492.",
  },
  {
    no: "51",
    name: "gyoro",
    chapter: "449",
    episode: "343",
    year: "2007",
    note: "-",
  },
  {
    no: "52",
    name: "gyoru",
    chapter: "001",
    episode: "045",
    year: "1997",
    note: "Namanya diungkapkan dalam Blue data book.",
  },
  {
    no: "53",
    name: "hocha",
    chapter: "391",
    episode: "275",
    year: "2005",
    note: "Namanya diungkapkan dalam Color Walk 4.",
  },
  {
    no: "54",
    name: "hyota",
    chapter: "196",
    episode: "120",
    year: "2001",
    note: "Namanya diungkapkan dalam Blue data book.",
  },
  {
    no: "55",
    name: "inhel",
    chapter: "718",
    episode: "648",
    year: "2013",
    note: "Namanya diungkapkan dalam SBS Volume 73.",
  },
  {
    no: "56",
    name: "issho",
    chapter: "701",
    episode: "630",
    year: "2013",
    note: "His alias was revealed by Sakazuki in Chapter 700. His real name was revealed in Chapter 705.",
  },
  {
    no: "57",
    name: "isuka",
    chapter: "-",
    episode: "-",
    year: "2018",
    note: "She was first introduced in One Piece novel A Volume 1.",
  },
  {
    no: "58",
    name: "jabra",
    chapter: "375",
    episode: "264",
    year: "2005",
    note: "-",
  },
  {
    no: "59",
    name: "jango",
    chapter: "025",
    episode: "009",
    year: "1998",
    note: "-",
  },
  {
    no: "60",
    name: "jerry",
    chapter: "362",
    episode: "253",
    year: "2005",
    note: "-",
  },
  {
    no: "61",
    name: "jigra",
    chapter: "860",
    episode: "830",
    year: "2017",
    note: "-",
  },
  {
    no: "62",
    name: "jinbe",
    chapter: "528",
    episode: "416",
    year: "2009",
    note: "Dia pertama kali disebutkan olehYosaku in Chapter 69.",
  },
  {
    no: "63",
    name: "jorge",
    chapter: "353",
    episode: "248",
    year: "2005",
    note: "Namanya diungkapkan dalam Blue Deep data book.",
  },
  {
    no: "64",
    name: "junan",
    chapter: "611",
    episode: "530",
    year: "2011",
    note: "Namanya diungkapkan dalam Blue Deep data book.",
  },
  {
    no: "65",
    name: "kadar",
    chapter: "622",
    episode: "541",
    year: "2011",
    note: "-",
  },
  {
    no: "66",
    name: "kaido",
    chapter: "795",
    episode: "739",
    year: "2015",
    note: "He was first mentionedby Gekko Moriah in Chapter 456. Part of his face was seen in Chapter 693 color spread.",
  },
  {
    no: "67",
    name: "kappa",
    chapter: "167",
    episode: "105",
    year: "2001",
    note: "-",
  },
  {
    no: "68",
    name: "karma",
    chapter: "553",
    episode: "467",
    year: "2009",
    note: "Namanya diungkapkan dalam Green data book.",
  },
  {
    no: "69",
    name: "karoo",
    chapter: "109",
    episode: "065",
    year: "1999",
    note: "-",
  },
  {
    no: "70",
    name: "kashi",
    chapter: "377",
    episode: "265",
    year: "2005",
    note: "-",
  },
  {
    no: "71",
    name: "camie",
    chapter: "195 (cover)",
    episode: "385",
    year: "2001",
    note: "She was formally introduced in Chapter 490.",
  },
  {
    no: "72",
    name: "kibin",
    chapter: "594",
    episode: "475",
    year: "2010",
    note: "Namanya diungkapkan dalam Episode 475 credits.",
  },
  {
    no: "73",
    name: "kikyo",
    chapter: "514",
    episode: "408",
    year: "2008",
    note: "-",
  },
  {
    no: "74",
    name: "kimel",
    chapter: "552",
    episode: "461",
    year: "2009",
    note: "Namanya diungkapkan dalam One Piece Magazine Vol.2.",
  },
  {
    no: "75",
    name: "kinga",
    chapter: "570",
    episode: "484",
    year: "2010",
    note: "Namanya diungkapkan dalam Green data book.",
  },
  {
    no: "76",
    name: "koala",
    chapter: "622",
    episode: "541",
    year: "2011",
    note: "-",
  },
  {
    no: "77",
    name: "kobee",
    chapter: "929",
    episode: "-",
    year: "2018",
    note: "-",
  },
  {
    no: "78",
    name: "konbu",
    chapter: "657",
    episode: "582",
    year: "2012",
    note: "Namanya diungkapkan dalam Chapter 686.",
  },
  {
    no: "79",
    name: "kuina",
    chapter: "005",
    episode: "002",
    year: "1997",
    note: "-",
  },
  {
    no: "80",
    name: "kukai",
    chapter: "552",
    episode: "461",
    year: "2009",
    note: "Namanya diungkapkan dalam One Piece Magazine Vol.2.",
  },
  {
    no: "81",
    name: "kuzan",
    chapter: "303",
    episode: "225",
    year: "2003",
    note: "Namanya diungkapkan dalam Chapter 318.",
  },
  {
    no: "82",
    name: "kyuin",
    chapter: "755",
    episode: "692",
    year: "2014",
    note: "-",
  },
  {
    no: "83",
    name: "kyuji",
    chapter: "302 (cover)",
    episode: "-",
    year: "2003",
    note: "Cover story character. Namanya diungkapkan dalam Blue Deep data book.",
  },
  {
    no: "85",
    name: "lines",
    chapter: "044",
    episode: "021",
    year: "1998",
    note: "Namanya diungkapkan dalam Blue data book.",
  },
  {
    no: "86",
    name: "lulis",
    chapter: "608",
    episode: "527",
    year: "2010",
    note: "Her name was revealed in the Blue Deep data book.",
  },
  {
    no: "87",
    name: "macro",
    chapter: "197 (cover)",
    episode: "386",
    year: "2001",
    note: "Namanya diungkapkan dalam Blue data book. He was formally introduced in Chapter 492.",
  },
  {
    no: "88",
    name: "magra",
    chapter: "582",
    episode: "493",
    year: "2010",
    note: "Namanya diungkapkan olehCurly Dadan in Chapter 584. He was formally identified in Chapter 587.",
  },
  {
    no: "89",
    name: "maidy",
    chapter: "215",
    episode: "129",
    year: "2002",
    note: "Her name was revealed in the Blue data book.",
  },
  {
    no: "90",
    name: "makko",
    chapter: "216",
    episode: "-",
    year: "2002",
    note: "Namanya diungkapkan dalam Blue data book.",
  },
  {
    no: "91",
    name: "marco",
    chapter: "234",
    episode: "151",
    year: "2002",
    note: "-",
  },
  {
    no: "92",
    name: "marie",
    chapter: "499",
    episode: "393",
    year: "2008",
    note: "-",
  },
  {
    no: "93",
    name: "marin",
    chapter: "500",
    episode: "394",
    year: "2008",
    note: "-",
  },
  {
    no: "94",
    name: "mario",
    chapter: "701",
    episode: "630",
    year: "2013",
    note: "-",
  },
  {
    no: "95",
    name: "mcguy",
    chapter: "551",
    episode: "460",
    year: "2009",
    note: "-",
  },
  {
    no: "96",
    name: "merry",
    chapter: "024",
    episode: "011",
    year: "1998",
    note: "Namanya diungkapkan olehKaya in Chapter 31.",
  },
  {
    no: "97",
    name: "mihar",
    chapter: "552",
    episode: "461",
    year: "2009",
    note: "Namanya diungkapkan dalam One Piece Magazine Vol.2.",
  },
  {
    no: "98",
    name: "milky",
    chapter: "814",
    episode: "765",
    year: "2016",
    note: "Her name was revealed in SBS Volume 82. First seen via photo in Chapter 807.",
  },
  {
    no: "99",
    name: "mocha",
    chapter: "657",
    episode: "582",
    year: "2012",
    note: "Her name was revealed in Chapter 665.",
  },
  {
    no: "100",
    name: "mochi",
    chapter: "274",
    episode: "180",
    year: "2003",
    note: "Namanya diungkapkan dalam Blue Deep data book.",
  },
  {
    no: "101",
    name: "mohji",
    chapter: "009",
    episode: "006",
    year: "1997",
    note: "Namanya diungkapkan dalam Chapter 12.",
  },
  {
    no: "102",
    name: "momoo",
    chapter: "073",
    episode: "031",
    year: "1999",
    note: "-",
  },
  {
    no: "103",
    name: "monda",
    chapter: "306",
    episode: "209",
    year: "2004",
    note: "-",
  },
  {
    no: "104",
    name: "monet",
    chapter: "657",
    episode: "581",
    year: "2012",
    note: "Her name was revealed in Chapter 662.",
  },
  {
    no: "105",
    name: "moyle",
    chapter: "272",
    episode: "178",
    year: "2003",
    note: "Namanya diungkapkan dalam Blue Deep data book.",
  },
  {
    no: "109",
    name: "mummy",
    chapter: "706",
    episode: "652",
    year: "2013",
    note: "-",
  },
  {
    no: "110",
    name: "muret",
    chapter: "223",
    episode: "146",
    year: "2002",
    note: "Her name was revealed in the Blue data book.",
  },
  {
    no: "111",
    name: "namur",
    chapter: "552",
    episode: "461",
    year: "2009",
    note: "Namanya diungkapkan dalam SBS Volume 58.",
  },
  {
    no: "112",
    name: "natto",
    chapter: "164",
    episode: "100",
    year: "2001",
    note: "Namanya diungkapkan dalam Blue data book.",
  },
  {
    no: "113",
    name: "ninth",
    chapter: "558",
    episode: "-",
    year: "2009",
    note: "Namanya diungkapkan dalam Green data book",
  },
  {
    no: "114",
    name: "nitro",
    chapter: "651",
    episode: "571",
    year: "2012",
    note: "Namanya diungkapkan dalam Chapter 827. He was first identified in Chapter 850.",
  },
  {
    no: "115",
    name: "nubon",
    chapter: "711",
    episode: "641",
    year: "2013",
    note: "Namanya diungkapkan dalam SBS Volume 73.",
  },
  {
    no: "116",
    name: "okame",
    chapter: "163",
    episode: "100",
    year: "2001",
    note: "Her name was revealed in the Blue data book.",
  },
  {
    no: "117",
    name: "okome",
    chapter: "224",
    episode: "146",
    year: "2002",
    note: "Namanya diungkapkan dalam Blue data book.",
  },
  {
    no: "118",
    name: "packy",
    chapter: "096",
    episode: "048",
    year: "1999",
    note: "Namanya diungkapkan dalam Blue data book.",
  },
  {
    no: "119",
    name: "palms",
    chapter: "553",
    episode: "470",
    year: "2009",
    note: "Namanya diungkapkan dalam Green data book.",
  },
  {
    no: "120",
    name: "pansy",
    chapter: "515",
    episode: "409",
    year: "2008",
    note: "Name seen on an arena battle board.",
  },
  {
    no: "121",
    name: "patty",
    chapter: "044",
    episode: "021",
    year: "1998",
    note: "-",
  },
  {
    no: "122",
    name: "pearl",
    chapter: "054",
    episode: "025",
    year: "1998",
    note: "-",
  },
  {
    no: "123",
    name: "pedro",
    chapter: "805",
    episode: "754",
    year: "2015",
    note: "-",
  },
  {
    no: "124",
    name: "poppy",
    chapter: "515",
    episode: "409",
    year: "2008",
    note: "Her name was seen on an arena battle board on Amazon Lily.",
  },
  {
    no: "125",
    name: "pound",
    chapter: "831",
    episode: "792",
    year: "2016",
    note: "Namanya diungkapkan dalam Chapter 835.",
  },
  {
    no: "126",
    name: "puppu",
    chapter: "155",
    episode: "092",
    year: "2000",
    note: "Namanya diungkapkan dalam Blue data book.",
  },
  {
    no: "127",
    name: "queen",
    chapter: "925",
    episode: "-",
    year: "2018",
    note: "He first appeared as a silhouette in Chapter 920.",
  },
  {
    no: "128",
    name: "raizo",
    chapter: "817",
    episode: "768",
    year: "2016",
    note: "His name was first mentioned by Kanjuro in Chapter 803.",
  },
  {
    no: "129",
    name: "ramba",
    chapter: "551",
    episode: "460",
    year: "2009",
    note: "Namanya diungkapkan olehthe Marines in Episode 460.",
  },
  {
    no: "130",
    name: "rampo",
    chapter: "711",
    episode: "641",
    year: "2013",
    note: "Namanya diungkapkan olehLeo in Chapter 733.",
  },
  {
    no: "131",
    name: "rindo",
    chapter: "516",
    episode: "410",
    year: "2008",
    note: "Her name was revealed in SBS Volume 54.",
  },
  {
    no: "132",
    name: "roche",
    chapter: "391",
    episode: "275",
    year: "2005",
    note: "His name revealed in Color Walk 4.",
  },
  {
    no: "133",
    name: "roddy",
    chapter: "805",
    episode: "754",
    year: "2015",
    note: "-",
  },
  {
    no: "134",
    name: "ronse",
    chapter: "550",
    episode: "459",
    year: "2009",
    note: "Namanya diungkapkan olehMarines in Chapter 556.",
  },
  {
    no: "135",
    name: "ryuma",
    chapter: "448",
    episode: "342",
    year: "2007",
    note: "Namanya diungkapkan olehHogback in Chapter 450.",
  },
  {
    no: "136",
    name: "saber",
    chapter: "552",
    episode: "461",
    year: "2009",
    note: "Namanya diungkapkan dalam One Piece Magazine Vol.2.",
  },
  {
    no: "137",
    name: "sanka",
    chapter: "608",
    episode: "527",
    year: "2010",
    note: "-",
  },
  {
    no: "138",
    name: "seira",
    chapter: "608",
    episode: "527",
    year: "2010",
    note: "Her name was revealed in SBS Volume 65.",
  },
  {
    no: "139",
    name: "shiki",
    chapter: "000",
    episode: "426",
    year: "2009",
    note: "Dia pertama kali disebutkan olehSengoku in Chapter 530.",
  },
  {
    no: "140",
    name: "shine",
    chapter: "214",
    episode: "128",
    year: "2002",
    note: "Namanya diungkapkan dalam Blue data book.",
  },
  {
    no: "141",
    name: "shion",
    chapter: "515",
    episode: "409",
    year: "2008",
    note: "Her name was seen on an arena battle board on Amazon Lily.",
  },
  {
    no: "142",
    name: "shura",
    chapter: "241",
    episode: "155",
    year: "2002",
    note: "Namanya diungkapkan dalam Chapter 248.",
  },
  {
    no: "143",
    name: "skull",
    chapter: "552",
    episode: "461",
    year: "2009",
    note: "Namanya diungkapkan dalam One Piece Magazine Vol.2.",
  },
  {
    no: "144",
    name: "sodom",
    chapter: "366",
    episode: "256",
    year: "2005",
    note: "-",
  },
  {
    no: "145",
    name: "speed",
    chapter: "917",
    episode: "-",
    year: "2018",
    note: "SDia pertama kali disebutkan olehKiku in Chapter 914.",
  },
  {
    no: "146",
    name: "spoil",
    chapter: "448",
    episode: "343",
    year: "2007",
    note: "Namanya diungkapkan oleha Thriller Bark Victim's Association member in Chapter 483.",
  },
  {
    no: "147",
    name: "stomp",
    chapter: "180",
    episode: "111",
    year: "2001",
    note: "Namanya diungkapkan dalam Blue data book.",
  },
  {
    no: "148",
    name: "stool",
    chapter: "134",
    episode: "081",
    year: "2000",
    note: "His name is written on his restaurant.",
  },
  {
    no: "149",
    name: "sugar",
    chapter: "682",
    episode: "608",
    year: "2012",
    note: "SDia pertama kali disebutkan olehJora in Chapter 718. She was identified in Chapter 731.",
  },
  {
    no: "150",
    name: "tacos",
    chapter: "905",
    episode: "-",
    year: "2018",
    note: "-",
  },
  {
    no: "151",
    name: "terry",
    chapter: "223",
    episode: "146",
    year: "2002",
    note: "Namanya diungkapkan dalam Blue data book.",
  },
  {
    no: "152",
    name: "tsuru",
    chapter: "234",
    episode: "151",
    year: "2002",
    note: "-",
  },
  {
    no: "153",
    name: "tsuru",
    chapter: "912",
    episode: "-",
    year: "2018",
    note: "Her name was revealed in Chapter 913.",
  },
  {
    no: "154",
    name: "turco",
    chapter: "598",
    episode: "517",
    year: "2010",
    note: "Namanya diungkapkan dalam Blue Deep data book.",
  },
  {
    no: "155",
    name: "usopp",
    chapter: "023",
    episode: "008",
    year: "1998",
    note: "-",
  },
  {
    no: "156",
    name: "vergo",
    chapter: "671",
    episode: "597",
    year: "2012",
    note: "Namanya diungkapkan dalam Chapter 672.",
  },
  {
    no: "157",
    name: "viola",
    chapter: "703",
    episode: "632",
    year: "2013",
    note: "Her real identity was revealed in Chapter 728.",
  },
  {
    no: "158",
    name: "vista",
    chapter: "552",
    episode: "000",
    year: "2009",
    note: "Namanya diungkapkan olehMihawk in Chapter 561.",
  },
  {
    no: "159",
    name: "vitan",
    chapter: "553",
    episode: "-",
    year: "2009",
    note: "Namanya diungkapkan dalam Green data book.",
  },
  {
    no: "160",
    name: "wanda",
    chapter: "804",
    episode: "753",
    year: "2015",
    note: "-",
  },
  {
    no: "161",
    name: "wanze",
    chapter: "367",
    episode: "257",
    year: "2005",
    note: "Dia pertama kali disebutkan olehCorgi in Chapter 362.",
  },
  {
    no: "162",
    name: "wapol",
    chapter: "131",
    episode: "079",
    year: "2000",
    note: "-",
  },
  {
    no: "163",
    name: "wicca",
    chapter: "705",
    episode: "635",
    year: "2013",
    note: "Her name and appearance revealed in Chapter 711.",
  },
  {
    no: "164",
    name: "wiper",
    chapter: "237",
    episode: "153",
    year: "2002",
    note: "Namanya diungkapkan dalam Chapter 249.",
  },
  {
    no: "165",
    name: "yonka",
    chapter: "608",
    episode: "527",
    year: "2010",
    note: "-",
  },
  {
    no: "166",
    name: "yorki",
    chapter: "103",
    episode: "063",
    year: "1999",
    note: "Namanya diungkapkan dalam Blue data book. He is then formally introduced by Brook in Chapter 486.",
  },
  {
    no: "167",
    name: "zadie",
    chapter: "391",
    episode: "275",
    year: "2005",
    note: "His name revealed in Color Walk 4.",
  },
  {
    no: "168",
    name: "zodia",
    chapter: "553",
    episode: "462",
    year: "2009",
    note: "Namanya diungkapkan dalam Green data book.",
  },
  {
    no: "169",
    name: "zucca",
    chapter: "564",
    episode: "489",
    year: "2009",
    note: "Namanya diungkapkan dalam Green data book.",
  },
];

export default solutionsData;
